# Generated by Django 2.1.2 on 2018-10-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='profile_picture',
        ),
    ]
