# Generated by Django 2.1.2 on 2018-11-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
