# Generated by Django 2.1.2 on 2018-11-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_friend_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
