# Generated by Django 2.1.2 on 2018-11-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181031_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
