# Generated by Django 2.1.2 on 2018-11-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_siteuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='friends',
        ),
    ]
