# Generated by Django 2.1.2 on 2018-11-11 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_siteuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='friends',
            field=models.ManyToManyField(related_name='User_Friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
