# Generated by Django 2.1.2 on 2018-11-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181111_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='profile_picture',
        ),
    ]
