# Generated by Django 2.1.2 on 2018-11-11 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friends',
            field=models.ManyToManyField(related_name='friendship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='friendship_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
