# Generated by Django 2.1.2 on 2018-11-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20181111_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friends',
        ),
    ]
