# Generated by Django 2.1.2 on 2018-11-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_remove_friendship_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
