# Generated by Django 2.1.2 on 2018-11-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionparticipant',
            old_name='participant_id',
            new_name='participant',
        ),
    ]
