# Generated by Django 2.1.2 on 2018-11-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_auto_20181108_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['created_time']},
        ),
    ]
