# Generated by Django 2.1.2 on 2018-11-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_auto_20181109_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussioncomment',
            options={'ordering': ['created_time']},
        ),
    ]
