# Generated by Django 2.1.2 on 2018-12-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_auto_20181111_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='discussioncomment',
            options={'ordering': ['-created_time']},
        ),
    ]
