# Generated by Django 2.1.2 on 2018-11-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['created_time']},
        ),
    ]
