# Generated by Django 2.1.2 on 2018-11-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20181117_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuscomment',
            options={'ordering': ['created_time']},
        ),
    ]
